### ISSUE TITLE
[BETA] Error occured while enabling

### ISSUE THREAD

**Issue by NullCase** [ElmHoe/PVPToggle#5]
Here is the log entry.

[01:14:23] [Server thread/INFO]: [PVPToggle] Enabling PVPToggle v1.0*
--
[01:14:23] [Server thread/INFO]: ----------- Attempting to enable PvPToggle -----------
[01:14:23] [Server thread/ERROR]: Error occurred while enabling PVPToggle v1.0 (Is it up to date?)
java.lang.NoClassDefFoundError: uk/co/ElmHoe/Bukkit/ConfigUtility
at uk.co.ElmHoe.Main.onEnable(Main.java:37) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-474]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.2.jar:git-Paper-474]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-474]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-474]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-474]
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[patched_1.13.2.jar:git-Paper-474]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[patched_1.13.2.jar:git-Paper-474]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[patched_1.13.2.jar:git-Paper-474]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-474]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-474]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.ClassNotFoundException: uk.co.ElmHoe.Bukkit.ConfigUtility
at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_191]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[patched_1.13.2.jar:git-Paper-474]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.13.2.jar:git-Paper-474]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
... 12 more
[01:14:23] [Server thread/INFO]: [PVPToggle] Disabling PVPToggle v1.0
[01:14:23] [Server thread/ERROR]: Error occurred while disabling PVPToggle v1.0 (Is it up to date?)
java.lang.NoClassDefFoundError: uk/co/ElmHoe/Bukkit/ConfigUtility
at uk.co.ElmHoe.Main.onDisable(Main.java:176) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:256) ~[patched_1.13.2.jar:git-Paper-474]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:359) ~[patched_1.13.2.jar:git-Paper-474]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437) ~[patched_1.13.2.jar:git-Paper-474]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) ~[patched_1.13.2.jar:git-Paper-474]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-474]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-474]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-474]
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[patched_1.13.2.jar:git-Paper-474]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[patched_1.13.2.jar:git-Paper-474]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[patched_1.13.2.jar:git-Paper-474]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-474]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-474]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]

**Comment by ElmHoe** [comment]
Uploaded a new build, apologies! I uploaded a jar without the correct libraries, I've not tested this one but that issue should be fixed. Thank you.

**Comment by NullCase** [comment]
I will try again next monday.

**Comment by NullCase** [comment]
This issue appears to be fixed.
